

<div class="container">


<div class="container" style="margin-top : 100px">
  
  <h1><p style="text-align : center">Come With Me</p></h1><?php echo "<br>"; ?>

</div>


<div class="row">
    <?php foreach ($pass as $pass): ?>
    <?php $colorbg = array("bg-info","bg-dark");
    $colorcbg = rand(0,1);
    for($i=0;$i<7;$i++){
        if($colorcbg == $i){
            $colorcbg = $colorbg[$i] ;
        }
    }
    ?>
    <div class="col-md-4">
        <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
            <div class="card-header">
                <?php if($pass->passStatus == 1){
                    echo "รับแล้ว" ;
                }else echo "รอรับ" ;
                ?>
            </div>
                <div class="card-body"> 
                    <p class="card-text">ชื่อ : <?php echo $pass->CusName ; ?></p>
                    <p class="card-text">นามสกุล : <?php echo $pass->CusSir ; ?></p>
                    <p class="card-text">จุดเริ่มต้น : <?php echo $pass->Here;?></p>
                    <p class="card-text">จุดหมายปลายทาง : <?php echo $pass->Going; ?></p>
                </div>
                <div class="card-footer">
                <button type="button" class="btn btn-success">ไปด้วย</button>
                
                </div>
        </div>
    </div>
    <?php endforeach; ?>
</div>

<?php
$date = strtotime("December 3, 2014 2:00 PM");
$remaining = $date - time();
$days_remaining = floor($remaining / 86400);
$hours_remaining = floor(($remaining % 86400) / 3600);
?>
 
<h1>There are <span class="green"> <?php echo $days_remaining?></span> days and <span class="green"> <?php echo $hours_remaining?></span> hours left</h1>
