

<div class="container">


<div class="container" style="margin-top : 100px">
  
  <h1><p style="text-align : center">Come With Me</p></h1><?php echo "<br>"; ?>

</div>


<div class="row">
    <?php foreach ($pass as $pass): ?>
    <?php $colorbg = array("bg-info","bg-dark");
    $colorcbg = rand(0,1);
    for($i=0;$i<7;$i++){
        if($colorcbg == $i){
            $colorcbg = $colorbg[$i] ;
        }
    }
    ?>
    <div class="col-md-4">
        <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
            <div class="card-header">
                <?php if($pass->passStatus == 1){
                    echo "รับแล้ว" ;
                }else echo "รอรับ" ;
                ?>
            </div>
                <div class="card-body"> 
                    <p class="card-text">ชื่อ : <?php echo $pass->CusName ; ?></p>
                    <p class="card-text">นามสกุล : <?php echo $pass->CusSir ; ?></p>
                    <p class="card-text">จุดเริ่มต้น : <?php echo $pass->Here;?></p>
                    <p class="card-text">จุดหมายปลายทาง : <?php echo $pass->Going; ?></p>
                </div>
                <div class="card-footer">
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModalCenter">ไปด้วย</button>

                
                </div>
        </div>
    </div>
    <?php endforeach; ?>
</div>

<?php
$date = strtotime("December 3, 2014 2:00 PM");
$remaining = $date - time();
$days_remaining = floor($remaining / 86400);
$hours_remaining = floor(($remaining % 86400) / 3600);
?>
 
<h1>There are <span class="green"> <?php echo $days_remaining?></span> days and <span class="green"> <?php echo $hours_remaining?></span> hours left</h1>


<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Who are you</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        
  
<div class="container">

<div class="row">
<div class="col">
  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text" id="inputGroup-sizing-default">First Name</span>
    </div>
    <input type="text" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default">
  </div>
</div>
<div class="col">
  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text" id="inputGroup-sizing-default">Last Name</span>
    </div>
    <input type="text" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default">
  </div>
</div>
<br>

</div>

<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="inputGroup-sizing-default">Number</span>
  </div>
  <input type="text" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default">
</div>

<div class="input-group mb-3">
  <div class="input-group-prepend">
    <label class="input-group-text" for="inputGroupSelect01">Stay</label>
  </div>
  <select class="custom-select" id="inputGroupSelect01">
    <option selected>Choose...</option>
    <option value="1">ลักษณานิเวศ 1</option>
    <option value="2">ลักษณานิเวศ 2</option>
    <option value="3">ลักษณานิเวศ 3</option>
    <option value="4">ลักษณานิเวศ 4</option>
    <option value="5">ลักษณานิเวศ 5</option>
    <option value="6">ลักษณานิเวศ 7</option>
    <option value="7">ลักษณานิเวศ 10</option>
    <option value="8">ลักษณานิเวศ 11</option>
    <option value="9">ลักษณานิเวศ 13</option>
    <option value="10">ลักษณานิเวศ 13</option>
    <option value="11">ลักษณานิเวศ 14</option>
    <option value="12">ลักษณานิเวศ 16</option>
    <option value="13">ลักษณานิเวศ 17</option>
    <option value="14">ลักษณานิเวศ 18</option>
    <option value="15">อาคารเรียนรวม 1</option>
    <option value="16">อาคารเรียนรวม 3</option>
    <option value="17">อาคารเรียนรวม 5</option>
    <option value="18">อาคารเรียนรวม 7</option>
    <option value="19">อาคารวิชาการ 1</option>
    <option value="20">อาคารวิชาการ 2</option>
    <option value="21">อาคารวิชาการ 3</option>
    <option value="22">อาคารวิชาการ 4</option>
    <option value="23">อาคารวิชาการ 5</option>
    <option value="24">อาคารวิชาการ 6</option>
    <option value="25">อาคารวิชาการ 7</option>
    <option value="26">อาคารวิชาการ 8</option>
    <option value="27">โรงกิจ</option>
    <option value="28">ศูนย์อาหารกลางคืน</option>
    <option value="29">โรงอาหาร 4</option>
    <option value="30">อาคารบริหาร</option>
    <option value="31">อาคารไทยบุรี</option>
    <option value="32">ศูนย์บรรณาสาร</option>
    <option value="33">ศูนย์คอมพิวเตอร์</option>
    <option value="34">อาคารนวัตกรรม</option>
    <option value="35">คิวรถตู้</option>
    <option value="36">ศูนย์กีฬา</option>
    <option value="37">สวนพฤษศาสตร์</option>
  </select>
</div>


<div class="input-group mb-3">
<div class="input-group-prepend">
  <label class="input-group-text" for="inputGroupSelect01">Go Go</label>
</div>
<select class="custom-select" id="inputGroupSelect01">
  <option selected>Choose...</option>
  <option value="1">ลักษณานิเวศ 1</option>
  <option value="2">ลักษณานิเวศ 2</option>
  <option value="3">ลักษณานิเวศ 3</option>
  <option value="4">ลักษณานิเวศ 4</option>
  <option value="5">ลักษณานิเวศ 5</option>
  <option value="6">ลักษณานิเวศ 7</option>
  <option value="7">ลักษณานิเวศ 10</option>
  <option value="8">ลักษณานิเวศ 11</option>
  <option value="9">ลักษณานิเวศ 13</option>
  <option value="10">ลักษณานิเวศ 13</option>
  <option value="11">ลักษณานิเวศ 14</option>
  <option value="12">ลักษณานิเวศ 16</option>
  <option value="13">ลักษณานิเวศ 17</option>
  <option value="14">ลักษณานิเวศ 18</option>
  <option value="15">อาคารเรียนรวม 1</option>
  <option value="16">อาคารเรียนรวม 3</option>
  <option value="17">อาคารเรียนรวม 5</option>
  <option value="18">อาคารเรียนรวม 7</option>
  <option value="19">อาคารวิชาการ 1</option>
  <option value="20">อาคารวิชาการ 2</option>
  <option value="21">อาคารวิชาการ 3</option>
  <option value="22">อาคารวิชาการ 4</option>
  <option value="23">อาคารวิชาการ 5</option>
  <option value="24">อาคารวิชาการ 6</option>
  <option value="25">อาคารวิชาการ 7</option>
  <option value="26">อาคารวิชาการ 8</option>
  <option value="27">โรงกิจ</option>
  <option value="28">ศูนย์อาหารกลางคืน</option>
  <option value="29">โรงอาหาร 4</option>
  <option value="30">อาคารบริหาร</option>
  <option value="31">อาคารไทยบุรี</option>
  <option value="32">ศูนย์บรรณาสาร</option>
  <option value="33">ศูนย์คอมพิวเตอร์</option>
  <option value="34">อาคารนวัตกรรม</option>
  <option value="35">คิวรถตู้</option>
  <option value="36">ศูนย์กีฬา</option>
  <option value="37">สวนพฤษศาสตร์</option>
</select>
</div>

</div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>