<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Startup UI Kit - Free Sample</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
		<link rel="shortcut icon" href="images/favicon.ico">
		<link rel="stylesheet" href="bootstrap/css/bootstrap.css">
		<link rel="stylesheet" href="css/font-awesome.min.css">
		<link rel="stylesheet" href="css/style.css">
		<link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,400i,700,700i|Montserrat:200,200i,300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
	</head>
	<body>
		
		<section class="cover-1 text-center">
			
			<div class="cover-container pb-5">
				<div class="cover-inner container">
					<h1 class="jumbotron-heading">Bring <em>Me</em> to <strong>Class</strong></h1>
					<p class="lead">สะดวกสบาย ใส่ใจบริการ ร่วมเดินทางไปด้วยกัน </p>
					<p>
						<a href="#" class="btn btn-primary btn-lg mb-2 mr-2 ml-2">Main call to action</a>
						<a href="#" class="btn btn-outline-white btn-lg mb-2 ml-2 ml-2">Secondary action</a>
					</p>
				</div>
			</div>
		</section>
	
		
		<section class="features-4 text-center">
			<div class="container">
				<div class="row justify-center">
					<div class="col-md-8 text-center" >
						<h2>Features</h2>
						<p class="lead mt-3">คิดออกเดี๋ยวใส่</p>
						<div class="divider"></div>
					</div>	
				</div>
				<div class="row">
					<div class="col-md-3 col-feature">
						<div class="rounded-circle justify-center">
							<em class="fa fa-2x fa-paint-brush"></em>
						</div>
						<h4>ลดมลพิษในรั้วมหาวิทยาลัย</h4>
						<p>ลดการสร้างมลพิษ รักสิ่งแวดล้อม </p>
					</div>
					<div class="col-md-3 col-feature">
						<div class="rounded-circle justify-center">
							<em class="fa fa-2x fa-mobile"></em>
						</div>
						<h4>ประหยัดน้ำมัน</h4>
						<p>ไปทางเดียวกัน จุดหมายเดียวกัน <br>ประหยัดน้ำมันได้มากโข</p>
					</div>
					<div class="col-md-3 col-feature">
						<div class="rounded-circle justify-center">
							<em class="fa fa-2x fa-code"></em>
						</div>
						<h4>สะดวก</h4>
						<p>สะดวกสบาย ปลอดภัย ใส่ใจกฎจราจร</p>
					</div>
					<div class="col-md-3 col-feature">
						<div class="rounded-circle justify-center">
							<em class="fa fa-2x fa-pencil"></em>
						</div>
						<h4>สร้างมิตรภาพ</h4>
						<p>มิตรภาพสร้างได้ทุกที่ไม่เว้นแม้บนท้องถนน</p>
					</div>
				</div>
			</div>
		</section>
		
		<section class="content-1">
			<div class="container">
				<div class="row justify-center">
					<div class="col-md-6 text-center">
						<img class="mb-4 img-fluid" src="images/placeholder-phone.png" >
					</div>
					<div class="col-md-6 text-center text-md-left" >
						<h2 class="mb-4 mt-4">Talk about your awesome features</h2>
						<p class="mb-4">Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
						<p><a class="btn btn-outline-secondary" href="#" role="button">Find out more	</a></p>
					</div>
				</div>
			</div>
		</section>
		
		<section class="content-2">
			<div class="container">
				<div class="row justify-center">
					<div class="col-md-6 text-center text-md-left pl-5">
						<h2 class="mb-4 mt-4">Talk about your awesome features</h2>
						<p class="mb-4">Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
						<p><a class="btn btn-outline-secondary" href="#" role="button">Find out more	</a></p>
					</div>
					<div class="col-md-6 text-center">
						<img class="mb-4 img-fluid" src="images/placeholder-beats-x.png" >
					</div>
				</div>
			</div>
		</section>
		
		<section class="content-4">
			<div class="container">
				<div class="row justify-center mt-5">
					<div class="col-md-6 pl-5 pr-5 text-center" >
						<img class="mb-4 img-fluid" src="images/placeholder-chair.jpg" >
					</div>
					<div class="col-md-6 text-left" >
						<h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h2>
						<p class="lead mt-4 mb-5">Integer libero nunc, elementum eu venenatis sed, molestie non tortor. Duis suscipit pulvinar justo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. </p>
						
						<div class="row">
							<div class="col-md-6 col-feature mb-4">
								<h4 class="mb-3">Clean Design</h4>
								<p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
							</div>
							<div class="col-md-6 col-feature mb-4">
								<h4 class="mb-3">Bootstrap 4</h4>
								<p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		
		<section class="cta-2 text-center">
			<div class="container">
				<h3 class="mt-2 mb-4">Sign up now to save 10% on your first order</h3>
				<form class="subscribe">
					<div class="form-group row pt-3">
						<div class="col-sm-8 mb-3">
							<input type="text" class="form-control-custom" id="inputName" placeholder="Your Name">
						</div>
						<div class="col-sm-4">
							<button type="submit" class="btn btn-lg btn-outline-success">Sign me up</button>
						</div>
					</div>
				</form>
			</div>
		</section>

		

		
		<section class="contact-2">
			<div class="container">
				<div class="row contact-details">
					<div class="col-sm-8 m-auto text-center">
						<h2>Contact Us</h2>
						<p class="lead constrain-width mt-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. At aliquam rhoncus donec magna turpis, dictum sit amet tellus at, commodo elementum sapien.</p>
						<div class="divider"></div>
						<h4>Ask us a question</h4>
						<form class="contact-form mt-4">
							<div class="row">
								<div class="col-md-6">
									<input type="text" class="form-control-custom mb-4" placeholder="Name" value="Your name">
								</div>
								<div class="col-md-6">
									<input type="text" class="form-control-custom mb-4" placeholder="Email address" value="Email address">
								</div>
								<br />
							</div>
							<div class="row">
								<div class="col-md-12">
									<textarea class="form-control-custom mb-4" rows="3">Your Message</textarea><br />
									<button type="submit" class="btn btn-primary btn-lg mb-4">Send Message</button>
								</div> 
							</div>
						</form>
					</div>
					
				</div>
			</div>
		</section>
		
	
		<footer class="footer-3">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<ul class="nav-footer mt-2 mt-md-0 ">
							<li class="nav-item active">
								<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">About</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">Our Work</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">Contact</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="container-fluid">
				<div class="divider"></div>
			</div>
			<div class="container">
				<div class="row">
					<div class="col-md-6 text-center text-md-left mt-2 mb-3 pt-1">
						<p>Copyright &copy; YourStartup. All rights reserved.</p>
					</div>
					<div class="col-md-6 text-center text-md-right mb-4">
						<ul class="social">
							<li><a href="#" title="Facebook" class="fa fa-facebook"></a></li>
							<li><a href="#" title="Twitter" class="fa fa-twitter"></a></li>
							<li><a href="#" title="Google+" class="fa fa-google"></a></li>
							<li><a href="#" title="Dribbble" class="fa fa-dribbble"></a></li>
							<li><a href="#" title="Instagram" class="fa fa-instagram"></a></li>
							<div class="clear"></div>
						</ul>
					</div>
				</div>
			</div>
		</footer>
		
		
		
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
		<script src="bootstrap/js/bootstrap.min.js"></script>

    </body>
</html>
