
		<section class="cover-1 text-center">
			

			<div class="cover-container pb-5">
				<div class="cover-inner container">
					<h1 class="jumbotron-heading">Bring <em>Me</em> to <strong>Class</strong></h1>
					<p class="lead">สะดวกสบาย ใส่ใจบริการ ร่วมเดินทางไปด้วยกัน </p>
					<p>
						<a href="#" class="btn btn-primary btn-lg mb-2 mr-2 ml-2">Main call to action</a>
						<a href="#" class="btn btn-outline-white btn-lg mb-2 ml-2 ml-2">Secondary action</a>
					</p>
				</div>
			</div>
		</section>
	
		
		<section class="features-4 text-center">
			<div class="container">
				<div class="row justify-center">
					<div class="col-md-8 text-center" >
						<h2>Features</h2>
						<p class="lead mt-3">ทางเดียวกันไปด้วยกัน</p>
						<div class="divider"></div>
					</div>	
				</div>
				<div class="row">
					<div class="col-md-3 col-feature">
						<div class="rounded-circle justify-center">
							<em class="fa fa-2x fa-tree"></em>
						</div>
						<h4>ลดมลพิษในรั้วมหาวิทยาลัย</h4>
						<p>ลดการสร้างมลพิษ รักสิ่งแวดล้อม </p>
					</div>
					<div class="col-md-3 col-feature">
						<div class="rounded-circle justify-center">
							<em class="fa fa-2x fa-recycle"></em>
						</div>
						<h4>ประหยัดน้ำมัน</h4>
						<p>ไปทางเดียวกัน จุดหมายเดียวกัน <br>ประหยัดน้ำมันได้มากโข</p>
					</div>
					<div class="col-md-3 col-feature">
						<div class="rounded-circle justify-center">
							<em class="fa fa-2x fa-bicycle"></em>
						</div>
						<h4>สะดวก</h4>
						<p>สะดวกสบาย ปลอดภัย ใส่ใจกฎจราจร</p>
					</div>
					<div class="col-md-3 col-feature">
						<div class="rounded-circle justify-center">
							<em class="fa fa-2x fa-male"></em>
						</div>
						<h4>สร้างมิตรภาพ</h4>
						<p>มิตรภาพสร้างได้ทุกที่ไม่เว้นแม้บนท้องถนน</p>
					</div>
				</div>
			</div>
		</section>
		
		<section class="content-1">
			<div class="container">
				<div class="row justify-center">
					<div class="col-md-6 text-center">
						<img class="mb-4 img-fluid" src="images/sm.png" >
					</div>
					<div class="col-md-6 text-center text-md-left" >
						<h2 class="mb-4 mt-4">Talk about your awesome features</h2>
						<p class="mb-4">Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
						<p><a class="btn btn-outline-secondary" href="#" role="button">Find out more	</a></p>
					</div>
				</div>
			</div>
		</section>
		
		<section class="content-2">
			<div class="container">
				<div class="row justify-center">
					<div class="col-md-6 text-center text-md-left pl-5">
						<h2 class="mb-4 mt-4">Talk about your awesome features</h2>
						<p class="mb-4">Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
						<p><a class="btn btn-outline-secondary" href="#" role="button">Find out more	</a></p>
					</div>
					<div class="col-md-6 text-center">
						<img class="mb-4 img-fluid" src="images/tree.png" >
					</div>
				</div>
			</div>
		</section>
		
		<section class="contact-2">
			<div class="container">
				<div class="row contact-details">
					<div class="col-sm-8 m-auto text-center">
						<h2>Contact Us</h2>
						<p class="lead constrain-width mt-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. At aliquam rhoncus donec magna turpis, dictum sit amet tellus at, commodo elementum sapien.</p>
						<div class="divider"></div>
						<h4>Ask us a question</h4>
						<form class="contact-form mt-4">
							<div class="row">
								<div class="col-md-6">
									<input type="text" class="form-control-custom mb-4" placeholder="Name" value="Your name">
								</div>
								<div class="col-md-6">
									<input type="text" class="form-control-custom mb-4" placeholder="Email address" value="Email address">
								</div>
								<br />
							</div>
							<div class="row">
								<div class="col-md-12">
									<textarea class="form-control-custom mb-4" rows="3">Your Message</textarea><br />
									<button type="submit" class="btn btn-primary btn-lg mb-4">Send Message</button>
								</div> 
							</div>
						</form>
					</div>
					
				</div>
			</div>
		</section>
		
	
		
		