
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Bring Me To Class</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">

        <li class="nav-item">
          <a class="nav-link" href="#">Customer</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Driver</a>
        </li>

      </ul>

    </div>
  </nav>
  <span class="navbar-brand mb-0 h1">Navbar</span>
</nav>
<div class="container">

  <center><img src="bgwu." alt="me" width="20%" height="8%"/></center>
