<div class="mapouter" style="margin-top : 100px; margin-left : 80px;">
   <div class="gmap_canvas"><a href="https://www.webdesign-muenchen-pb.de"></a><iframe width="1080" height="620" id="gmap_canvas" src="https://maps.google.com/maps?q=walailak university &t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe></div>
   <style>.mapouter{overflow:hidden;height:620px;width:1080px;}.gmap_canvas {background:none!important;height:620px;width:1080px;}</style>
</div>